// main/app/admin/blogs/page.tsx
'use client'
import { Nav } from '@/app/components/general/nav'
import VerifyLayout, { PageVerifyType } from '@/app/components/general/verifyLayout';
import { deleteBlog, getBlogs } from '@/public/utils/blogUtils';
import { User } from '@/types/authtypes';
import { BlogType } from '@/types/types';
import Image from 'next/image'
import React, { useEffect, useState } from 'react'


export default function AdminBlogs() {
	const [exps, setExps] = useState<BlogType[]>([]);
	const [rows, setRows] = useState<BlogType[]>([]);
	const [deleteConfirm, setDeleteConfirm] = useState<string>("");
	const [searchText, setSearchText] = useState<string>("");

	function verify(user: User | undefined): PageVerifyType {
		const pv: PageVerifyType = {
			accepted: false,
			rejectMsg: "You must be a logged in admin to visit this page.",
			url: "/",
		}

		if (!user) {
			return pv;
		
		} else if (!user.isAdmin) {
			pv.rejectMsg = "You must be an admin to visit this page.";
			return pv;
		
		} else {
			pv.accepted = true;
			pv.rejectMsg = "";
			return pv;
		}
	}
	
	async function handleDelete(blog: BlogType) {
		const res = await deleteBlog(blog);
		if (!res.error) {
			setExps(prev => prev.filter(x => blog.title != x.title));
			setRows(prev => prev.filter(x => blog.title != x.title));
		}
	}

	async function handleSearch(searchText: string) {
		setRows(exps.filter(experience => experience.title.toLowerCase().includes(searchText.toLowerCase())));
	}

	async function refreshExps() {
		const res = await getBlogs();
		if (!res.error) {
			setExps(res.unwrap());
			setRows(res.unwrap());
		}
	}

	useEffect(() => {
		refreshExps();
	}, []);

	function dateFormat(date: Date) {
		return date.toLocaleDateString('en-US', { timeZone: 'America/New_York' });
	}

	return (
		<div className='w-full text-white'>
			<Nav alwaysOn />
			
			<VerifyLayout verify={verify}>
				<div className='w-full flex flex-col gap-10 items-center mt-[150px]'>
					<div>
						<Image
							width={300}
							height={300}
							alt="Writer Evan"
							src="/blogs.png"
							priority
						/>
						<p className='text-[40px] text-center mt-5'>Blogs</p>
					</div>
			
					<div className='p-3 w-[100%] flex gap-3 justify-center static'>
						<input type="text" onChange={e => setSearchText(e.target.value)} placeholder='Search by title!' className='w-[60vw] rounded-full py-3 px-4 text-black z-10 bg-white'/>
						<button
							onClick={() => handleSearch(searchText)}
							className='bg-blue-600 hover:bg-blue-700 text-white px-3 rounded-[10px]'
						>Search</button>
						<a
							href='/admin/blogs/create'
						><div className='bg-green-600 hover:bg-green-700 text-white px-3 rounded-[10px] h-full flex items-center'>Create</div></a>
					</div>
			
					{rows.length == 0 && <p className='text-3xl text-neutral-400'>No Results</p>}

					<div className='flex flex-wrap justify-center items-stretch gap-5 w-[80%] pb-20'>
						{rows.map((blog, idx) =>
							<div key={idx} className='text-white p-3 border-white border-2 rounded-[15px] bg-black flex w-full'>
								<div className='w-[90%]'>
									<p className='text-lg'><b>{blog.title}</b></p>
									<p className='text-neutral-300'>{dateFormat(blog.postdate)}</p>
									<p className='mt-5'>{blog.summary}</p>
								</div>
								<div className='w-[10%] flex flex-col items-end justify-center gap-5'>
									<button
										onClick={(e) => {
											e.stopPropagation();
											if (deleteConfirm == blog.title) {
												handleDelete(blog)
												setDeleteConfirm("");
											} else {
												setDeleteConfirm(blog.title);
											}
										}}
										className='opacity-50 hover:opacity-100 cursor-pointer'
									>
										<Image
											width={30}
											height={30}
											alt="Check Icon"
											src={deleteConfirm == blog.title ? "/svgs/wcheck.svg" : "/svgs/wtrash.svg"}
										/>
									</button>

									<a
										href={`/admin/blogs/${blog.title.replaceAll(" ", "+")}`}
										className='opacity-50 hover:opacity-100 cursor-pointer'
									>
										<Image
											width={30}
											height={30}
											alt="Edit Icon"
											src="/svgs/wedit.svg"
										/>
									</a>
								</div>
							</div>
						)}
					</div>
				</div>
			</VerifyLayout>
		</div>
	)	
}

// manager/src/routes/blogs/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Navbar from '$lib/components/Navbar.svelte';
	import BlogSide from '$lib/components/BlogSide.svelte';
	import BlogImg from '$lib/public/blogs.png';
	import TrashImg from '$lib/public/wtrash.svg';
	import CheckImg from '$lib/public/wcheck.svg';
  	import type { Blog } from '$lib/types/types';
  	import { DeleteBlog, GetBlogs } from '$lib/actions/blogActions';


	let blogs = $state<Blog[]>([]);
	let searchText = $state<string>("");
	let deleteConfirm = $state<string>("");
	let hideSidePage = $state<boolean>(true);
	let newTitle = $state<string>("");
	let newSummary = $state<string>("");
	let newContent = $state<string>("");
	let newPostdate = $state<string>("");


	async function refreshBlogs() {
		blogs = await GetBlogs("")
	}
	

	onMount(async () => {
		blogs = await GetBlogs("")
	})
</script>


<div class="relative">
	<Navbar />
	<BlogSide bind:toHide={hideSidePage} bind:newTitle={newTitle} bind:newSummary={newSummary} bind:newContent={newContent} bind:newPostdate={newPostdate} refreshBlogs={refreshBlogs}/>

	<div class='w-[100%] my-[4vh] flex flex-col justify-center items-center p-3 relative'>
		<img src={BlogImg} alt="blog display">
		<p class='text-neutral-200 mt-5'>Welcome to the blogs page!</p>

		<div class='absolute left-0 bottom-[10vh] rotate-[30deg] z-0 w-[48vw] min-w-[200px] h-[14vh] -ml-[28vh] rounded-full blur-[10vh] bg-green-800'></div>
		<div class='absolute left-0 bottom-0 rotate-[30deg] z-0 w-[20vw] h-[10vh] -ml-[7vh] rounded-full blur-[7vh] bg-green-600'></div>
	</div>


	<div class='p-3 w-[100%] flex gap-3 justify-center static'>
		<input type="text" bind:value={searchText} placeholder='Search or scroll!' class='w-[60vw] rounded-full py-3 px-4 text-black z-10'/>
		<button onclick={async () => {
			blogs = await GetBlogs(searchText)
		}} class='bg-blue-500 hover:bg-blue-400 text-white px-3 rounded-[10px]'>Search</button>
		<button
			id="openBtn"
			onclick={() => {
				newTitle = ""
				newSummary = ""
				newContent = ""
				newPostdate = ""
				if (hideSidePage) hideSidePage = false;
			}}
			class='bg-green-500 hover:bg-green-400 text-white px-3 rounded-[10px]'
		>New Blog</button>
	</div>

	<div class='flex flex-col gap-[25px] w-[100%] justify-center items-center px-5 pb-[50px] pt-[50px]'>
		{#each blogs as blog}
			<div class="w-[100%] relative">
				<button
					id="openBtn"
					onclick={async () => {
						newTitle = blog.title
						newSummary = blog.summary
						newContent = blog.content
						newPostdate = blog.postdate
						if (hideSidePage) hideSidePage = false;
					}}
					class='z-20 text-start text-white p-3 border-white border-2 rounded-[15px] bg-black w-[100%]'
				>
					<div class="w-[80%]">
						<p id="openBtn" class='text-lg'><b>{blog.title}</b></p>
						<p id="openBtn" class='text-neutral-300'>{blog.postdate}</p>
						<br id="openBtn"/>
						<p id="openBtn">{blog.summary}</p>
					</div>
	
				</button>
				<button onclick={async () => {
					if (deleteConfirm == blog.title) {
						deleteConfirm = ""
						await DeleteBlog(blog.title)
						await refreshBlogs()
					} else {
						deleteConfirm = blog.title
					}
				}} class="absolute top-[50%] right-[20px] -translate-x-[50%] -translate-y-[50%] h-[35px] w-[35px] opacity-70 hover:opacity-100">
					{#if deleteConfirm == blog.title}
						<img src={CheckImg} alt="A Check Mark">
					{:else}
						<img src={TrashImg} alt="A Trash Can">
					{/if}
				</button>
			</div>
		{/each}
		{#if blogs.length == 0}
			<p class='text-neutral-300 text-3xl'>No Results</p>
		{/if}
	</div>
</div>
